import { CA_PROVINCES, GB_NATIONS, IN_PT_STATES } from "@/lib/paycheck/international";
import { STATE_TAX_RATES } from "@/lib/paycheck/us";
import type { CountryCode, PayStubCountryProfile } from "./types";

function amountEarning(label: string, amount: number) {
  return { label, mode: "amount" as const, hours: 0, rate: 0, amount };
}

function hoursEarning(label: string, hours: number, rate: number) {
  return { label, mode: "hours" as const, hours, rate, amount: 0 };
}

export const PAY_STUB_COUNTRIES: PayStubCountryProfile[] = [
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    currency: "USD",
    locale: "en-US",
    ruleNote: "Based on 2026 US Federal tax rules (IRS Rev. Proc. 2025-32) plus FICA. State tax is a simplified estimate.",
    documentTitle: "EARNINGS STATEMENT",
    documentName: "Pay stub",
    employerLabel: "Employer",
    employeeIdLabel: "Employee ID",
    jobTitleLabel: "Job title",
    nationalIdLabel: "SSN (last 4 digits only)",
    nationalIdPrefix: "XXX-XX-",
    departmentLabel: "Department",
    regionLabel: "State",
    regions: STATE_TAX_RATES.map((state) => ({ code: state.code, name: state.name })),
    defaultRegion: "CA",
    defaultFrequency: "biweekly",
    defaultRetirementPercent: 0,
    retirementLabel: "401(k) contribution (%)",
    companyName: "Acme Corp",
    companyAddress: "123 Business Ave, San Francisco, CA 94102",
    employeeName: "Jane Smith",
    employeeAddress: "456 Home St, Oakland, CA 94601",
    defaultEarnings: [hoursEarning("Regular Pay", 80, 37.5)],
    bonusLabel: "Bonus",
    allowanceLabel: "Allowance",
    hoursEarningLabel: "Overtime",
    otherDeductionLabel: "Health Insurance",
  },
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    currency: "INR",
    locale: "en-IN",
    ruleNote: "Based on India FY 2025-26 new tax regime plus EPF (12% of basic), ESI, and professional tax. Sample salary slip only.",
    documentTitle: "SALARY SLIP",
    documentName: "Salary slip",
    employerLabel: "Employer",
    employeeIdLabel: "Employee code",
    jobTitleLabel: "Designation",
    nationalIdLabel: "PAN (last 4 characters)",
    nationalIdPrefix: "XXXXXX",
    departmentLabel: "Department",
    regionLabel: "Professional tax state",
    regions: IN_PT_STATES.map((state) => ({ code: state.code, name: state.name })),
    defaultRegion: "KA",
    defaultFrequency: "monthly",
    defaultRetirementPercent: 12,
    retirementLabel: "EPF (% of basic)",
    companyName: "Acme India Pvt Ltd",
    companyAddress: "12 MG Road, Bengaluru, Karnataka 560001",
    employeeName: "A. Sharma",
    employeeAddress: "88 Indiranagar, Bengaluru, Karnataka 560038",
    defaultEarnings: [
      amountEarning("Basic", 25_000),
      amountEarning("HRA", 10_000),
      amountEarning("Special Allowance", 15_000),
    ],
    bonusLabel: "Bonus",
    allowanceLabel: "Conveyance Allowance",
    hoursEarningLabel: "Overtime",
    otherDeductionLabel: "Health Insurance",
  },
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    currency: "GBP",
    locale: "en-GB",
    ruleNote: "Based on UK 2025/26 PAYE and Class 1 National Insurance. Pension is treated as salary sacrifice when a percent is set.",
    documentTitle: "PAYSLIP",
    documentName: "Payslip",
    employerLabel: "Employer",
    employeeIdLabel: "Payroll number",
    jobTitleLabel: "Job title",
    nationalIdLabel: "NI number (last 4 characters)",
    nationalIdPrefix: "XX ",
    departmentLabel: "Department",
    regionLabel: "Tax nation",
    regions: GB_NATIONS.map((nation) => ({ code: nation.code, name: nation.name })),
    defaultRegion: "ENG",
    defaultFrequency: "monthly",
    defaultRetirementPercent: 5,
    retirementLabel: "Pension / salary sacrifice (%)",
    companyName: "Acme Ltd",
    companyAddress: "14 King Street, London EC2V 8EA",
    employeeName: "Jane Smith",
    employeeAddress: "22 Baker Street, London W1U 3BW",
    defaultEarnings: [amountEarning("Basic Salary", 3_750)],
    bonusLabel: "Bonus",
    allowanceLabel: "Allowance",
    hoursEarningLabel: "Overtime",
    otherDeductionLabel: "Student Loan",
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    currency: "CAD",
    locale: "en-CA",
    ruleNote: "Based on 2025 Canadian federal tax, CPP/EI, and a simplified provincial estimate.",
    documentTitle: "PAY STATEMENT",
    documentName: "Pay stub",
    employerLabel: "Employer",
    employeeIdLabel: "Employee ID",
    jobTitleLabel: "Job title",
    nationalIdLabel: "SIN (last 4 digits only)",
    nationalIdPrefix: "XXX-XXX-",
    departmentLabel: "Department",
    regionLabel: "Province / territory",
    regions: CA_PROVINCES.map((province) => ({ code: province.code, name: province.name })),
    defaultRegion: "ON",
    defaultFrequency: "biweekly",
    defaultRetirementPercent: 0,
    retirementLabel: "RRSP contribution (%)",
    companyName: "Acme Canada Inc",
    companyAddress: "100 King Street West, Toronto, ON M5X 1A9",
    employeeName: "Jane Smith",
    employeeAddress: "48 Queen Street, Toronto, ON M5H 2M3",
    defaultEarnings: [hoursEarning("Regular Pay", 80, 40.87)],
    bonusLabel: "Bonus",
    allowanceLabel: "Allowance",
    hoursEarningLabel: "Overtime",
    otherDeductionLabel: "Benefits",
  },
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    currency: "AUD",
    locale: "en-AU",
    ruleNote: "Based on Australia 2025–26 resident PAYG brackets and 2% Medicare levy. Employer Super is typically paid on top of salary and is not deducted here unless salary-sacrificed.",
    documentTitle: "PAYSLIP",
    documentName: "Payslip",
    employerLabel: "Employer",
    employeeIdLabel: "Employee ID",
    jobTitleLabel: "Job title",
    nationalIdLabel: "TFN (last 4 digits only)",
    nationalIdPrefix: "XXX XXX ",
    departmentLabel: "Department",
    regionLabel: null,
    regions: [],
    defaultRegion: "AU",
    defaultFrequency: "monthly",
    defaultRetirementPercent: 0,
    retirementLabel: "Salary-sacrificed super (%)",
    companyName: "Acme Australia Pty Ltd",
    companyAddress: "1 Martin Place, Sydney NSW 2000",
    employeeName: "Jane Smith",
    employeeAddress: "18 George Street, Sydney NSW 2000",
    defaultEarnings: [amountEarning("Base Salary", 7_917)],
    bonusLabel: "Bonus",
    allowanceLabel: "Allowance",
    hoursEarningLabel: "Overtime",
    otherDeductionLabel: "Health Insurance",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    currency: "AED",
    locale: "en-AE",
    ruleNote: "UAE has no federal personal income tax on salary. Net pay equals gross minus optional deductions you enter.",
    documentTitle: "SALARY CERTIFICATE / PAYSLIP",
    documentName: "Payslip",
    employerLabel: "Employer",
    employeeIdLabel: "Employee ID",
    jobTitleLabel: "Job title",
    nationalIdLabel: "Emirates ID (last 4 digits only)",
    nationalIdPrefix: "XXX-XXXX-",
    departmentLabel: "Department",
    regionLabel: null,
    regions: [],
    defaultRegion: "AE",
    defaultFrequency: "monthly",
    defaultRetirementPercent: 0,
    retirementLabel: "Pension / savings (%)",
    companyName: "Acme Middle East LLC",
    companyAddress: "Sheikh Zayed Road, Dubai, United Arab Emirates",
    employeeName: "Jane Smith",
    employeeAddress: "Marina Walk, Dubai, United Arab Emirates",
    defaultEarnings: [
      amountEarning("Basic Salary", 10_000),
      amountEarning("Housing Allowance", 6_000),
      amountEarning("Transport Allowance", 4_000),
    ],
    bonusLabel: "Bonus",
    allowanceLabel: "Other Allowance",
    hoursEarningLabel: "Overtime",
    otherDeductionLabel: "Health Insurance",
  },
];

export function getPayStubCountry(code: CountryCode) {
  return PAY_STUB_COUNTRIES.find((country) => country.code === code) ?? PAY_STUB_COUNTRIES[0];
}
