import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlarmClock,
  AlignLeft,
  Aperture,
  AppWindow,
  ArrowUpAZ,
  BadgeCheck,
  Barcode,
  Binary,
  Braces,
  Building2,
  Cake,
  Calculator,
  CalendarDays,
  Car,
  CaseSensitive,
  Clock,
  Code,
  Coins,
  Combine,
  CopyX,
  Crop,
  Database,
  DatabaseZap,
  Dices,
  Droplet,
  Eraser,
  FileDown,
  FileImage,
  FileJson,
  FileOutput,
  FileSpreadsheet,
  FileText,
  FileType,
  FileUp,
  GraduationCap,
  FlipHorizontal,
  GitCompare,
  Globe,
  Hash,
  Home,
  Hourglass,
  IdCard,
  Image,
  ImageMinus,
  ImagePlus,
  IndianRupee,
  Key,
  KeyRound,
  Landmark,
  Link,
  Link2,
  ListChecks,
  ListOrdered,
  Lock,
  MapPin,
  Mic,
  Paintbrush,
  Palette,
  Percent,
  Pipette,
  QrCode,
  Receipt,
  RefreshCcw,
  Regex,
  Replace,
  RotateCw,
  Ruler,
  Scaling,
  Scissors,
  Stamp,
  StickyNote,
  SwatchBook,
  Table,
  Tag,
  Tags,
  Timer,
  TrendingUp,
  Type,
  Unlock,
  Users,
  Volume2,
  Wallet,
  WholeWord,
  Wrench,
} from "lucide-react";
import type { CategoryId, ToolIconName } from "./registry";

const ICONS: Record<ToolIconName, LucideIcon> = {
  FileDown,
  Combine,
  Scissors,
  RotateCw,
  FileType,
  Table,
  FileImage,
  ImagePlus,
  Lock,
  Unlock,
  FileOutput,
  Eraser,
  Stamp,
  ListOrdered,
  Image,
  Scaling,
  Crop,
  RefreshCcw,
  ImageMinus,
  FileUp,
  Palette,
  Pipette,
  Aperture,
  Percent,
  Cake,
  Calculator,
  Landmark,
  Home,
  Wallet,
  Receipt,
  Tag,
  Activity,
  CalendarDays,
  Timer,
  Coins,
  TrendingUp,
  Ruler,
  Type,
  WholeWord,
  CaseSensitive,
  AlignLeft,
  CopyX,
  ArrowUpAZ,
  FlipHorizontal,
  GitCompare,
  Link2,
  Replace,
  Braces,
  BadgeCheck,
  Binary,
  Hash,
  Link,
  KeyRound,
  Code,
  Paintbrush,
  Regex,
  Clock,
  Droplet,
  FileJson,
  FileSpreadsheet,
  Database,
  QrCode,
  Key,
  Dices,
  Barcode,
  AppWindow,
  DatabaseZap,
  SwatchBook,
  Tags,
  AlarmClock,
  Hourglass,
  ListChecks,
  StickyNote,
  Mic,
  Globe,
  Users,
  IdCard,
  IndianRupee,
  Building2,
  MapPin,
  Car,
  Volume2,
};

export function getToolIcon(name: ToolIconName): LucideIcon {
  return ICONS[name];
}

export const CATEGORY_ICONS: Record<CategoryId, LucideIcon> = {
  pdf: FileText,
  image: Image,
  text: Type,
  developer: Code,
  finance: Calculator,
  student: GraduationCap,
  productivity: Timer,
  other: Wrench,
};

export const CATEGORY_STYLES: Record<CategoryId, { iconBg: string; iconFg: string }> = {
  pdf: { iconBg: "bg-canvas", iconFg: "text-[var(--coral)]" },
  image: { iconBg: "bg-canvas", iconFg: "text-[var(--accent-amber)]" },
  text: { iconBg: "bg-canvas", iconFg: "text-[var(--accent-amber)]" },
  developer: { iconBg: "bg-canvas", iconFg: "text-ink" },
  finance: { iconBg: "bg-canvas", iconFg: "text-[var(--accent-teal)]" },
  student: { iconBg: "bg-canvas", iconFg: "text-[var(--accent-teal)]" },
  productivity: { iconBg: "bg-canvas", iconFg: "text-[var(--accent-teal)]" },
  other: { iconBg: "bg-canvas", iconFg: "text-[var(--coral)]" },
};
